# Generated by Django 5.2.7 on 2025-10-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('slug', models.SlugField(help_text='Versión del título amigable para URLs (ej: sobre-mi)', max_length=200, unique=True)),
            ],
        ),
    ]
