# Generated by Django 5.2.7 on 2025-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='contenido',
        ),
        migrations.AddField(
            model_name='pagina',
            name='contenido_principal',
            field=models.TextField(blank=True, help_text='El párrafo de introducción o biografía principal.', null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='La foto principal que aparecerá en la página.', null=True, upload_to='paginas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='seccion_extra_contenido',
            field=models.TextField(blank=True, help_text='Contenido para la sección secundaria.', null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='seccion_extra_titulo',
            field=models.CharField(blank=True, help_text='Título para la sección secundaria (ej: Mi Filosofía).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Una frase corta que aparece debajo del título principal.', max_length=255, null=True),
        ),
    ]
