# Generated by Django 5.2.7 on 2025-11-06 23:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_remove_pagina_contenido_pagina_contenido_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='imagen_principal',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='La foto principal que aparecerá en la página.', null=True, upload_to='paginas/'),
        ),
    ]
