# Generated by Django 5.2.7 on 2025-10-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Correo Argentino (Domicilio)', max_length=100)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Entrega 3-5 días hábiles', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar este método a los clientes.')),
            ],
            options={
                'verbose_name': 'Método de Envío',
                'verbose_name_plural': 'Métodos de Envío',
            },
        ),
        migrations.CreateModel(
            name='RangoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_desde', models.PositiveIntegerField(help_text='Código postal inicial del rango (ej: 1000)')),
                ('cp_hasta', models.PositiveIntegerField(help_text='Código postal final del rango (ej: 1900)')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio específico para este rango.', max_digits=10)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='envios.metodoenvio')),
            ],
            options={
                'verbose_name': 'Rango Postal',
                'verbose_name_plural': 'Rangos Postales',
                'ordering': ['cp_desde'],
            },
        ),
    ]
