# Generated by Django 5.2.7 on 2025-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu_alias', models.CharField(help_text='Tu CBU o Alias para transferencias.', max_length=255)),
                ('link_mercado_pago', models.URLField(help_text='El enlace de pago de Mercado Pago.', max_length=400)),
            ],
            options={
                'verbose_name': 'Datos de Pago',
            },
        ),
    ]
