# Generated by Django 5.2.7 on 2025-10-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo', models.ImageField(help_text='Imagen principal de la sección (se recomienda tamaño grande).', upload_to='hero_images/', verbose_name='Imagen de Fondo')),
                ('titulo_principal', models.CharField(help_text='Ej: Te ayudamos a lograr tus objetivos, sin perder el placer de comer.', max_length=200, verbose_name='Título Principal')),
                ('descripcion', models.TextField(help_text='Texto descriptivo debajo del título.', verbose_name='Descripción')),
                ('texto_boton_1', models.CharField(default='Viandas', max_length=50, verbose_name='Texto Botón 1')),
                ('url_boton_1', models.URLField(default='/productos/', verbose_name='URL Botón 1')),
                ('texto_boton_2', models.CharField(default='Consultas', max_length=50, verbose_name='Texto Botón 2')),
                ('url_boton_2', models.URLField(default='/turnos/', verbose_name='URL Botón 2')),
                ('activa', models.BooleanField(default=True, help_text='Marca esta opción para que esta configuración sea la visible.', verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Configuración de Sección Principal',
                'verbose_name_plural': 'Configuraciones de Sección Principal',
            },
        ),
    ]
