# Generated by Django 5.2.7 on 2025-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_herosectionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Este texto aparecerá sobre la imagen.', max_length=200, null=True, verbose_name='Título (Opcional)')),
                ('imagen', models.ImageField(help_text='Sube la imagen para este slide.', upload_to='carrusel/', verbose_name='Imagen del carrusel')),
                ('link_url', models.URLField(blank=True, help_text='URL a la que dirigirá la imagen (ej: /productos/)', max_length=300, null=True, verbose_name='Enlace (Opcional)')),
                ('abrir_en_nueva_pestana', models.BooleanField(default=False, verbose_name='Abrir en nueva pestaña')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de aparición (menor número primero).')),
                ('activo', models.BooleanField(default=True, help_text='Desmarca esta casilla para ocultar esta imagen del carrusel.', verbose_name='¿Mostrar esta imagen?')),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['orden'],
            },
        ),
    ]
