# Generated by Django 5.2.7 on 2025-10-23 19:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_carruselimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AparienciaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo_body', colorfield.fields.ColorField(default='#ECF0E5', help_text='El color de fondo general de la página.', image_field=None, max_length=25, samples=None, verbose_name='Color de Fondo Principal')),
                ('color_navbar', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color de Fondo de Navbar y Footer')),
                ('color_principal_botones', colorfield.fields.ColorField(default='#78857A', image_field=None, max_length=25, samples=None, verbose_name='Color Principal (Botones y Acentos)')),
                ('color_hover_botones', colorfield.fields.ColorField(default='#647066', image_field=None, max_length=25, samples=None, verbose_name='Color Hover (Botones y Acentos)')),
                ('color_texto_botones', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color de Texto (Botones)')),
            ],
            options={
                'verbose_name': 'Configuración de Apariencia',
                'verbose_name_plural': 'Configuración de Apariencia',
            },
        ),
    ]
