# Generated by Django 5.2.7 on 2025-10-23 21:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_aparienciaconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparienciaconfig',
            old_name='color_texto_botones',
            new_name='boton_color_principal_texto',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='color_hover_botones',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='color_navbar',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='color_principal_botones',
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='boton_color_principal_fondo',
            field=colorfield.fields.ColorField(default='#78857A', image_field=None, max_length=25, samples=None, verbose_name='Color Principal (Botones)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='boton_color_principal_hover',
            field=colorfield.fields.ColorField(default='#647066', image_field=None, max_length=25, samples=None, verbose_name='Color Hover (Botones)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='boton_color_secundario_borde',
            field=colorfield.fields.ColorField(default='#78857A', image_field=None, max_length=25, samples=None, verbose_name='Color Secundario (Borde y Texto)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='navbar_color_enlaces',
            field=colorfield.fields.ColorField(default='#555555', image_field=None, max_length=25, samples=None, verbose_name='Color de Texto (Enlaces del Nav)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='navbar_color_fondo',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color de Fondo (Navbar y Footer)'),
        ),
        migrations.AlterField(
            model_name='aparienciaconfig',
            name='color_fondo_body',
            field=colorfield.fields.ColorField(default='#ECF0E5', image_field=None, max_length=25, samples=None, verbose_name='Color de Fondo Principal'),
        ),
    ]
