# Generated by Django 5.2.7 on 2025-10-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_rename_color_texto_botones_aparienciaconfig_boton_color_principal_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='estilo_tarjeta_producto',
            field=models.CharField(choices=[('simple', 'Estilo Simple (Actual)'), ('hot_sale', 'Estilo "Hot Sale" (Con insignia)'), ('futurista', 'Estilo "Futurista" (Animado)')], default='simple', help_text='Elige el diseño que se usará para mostrar los productos en el catálogo.', max_length=20, verbose_name='Estilo de Tarjetas de Producto'),
        ),
    ]
