# Generated by Django 5.2.7 on 2025-10-28 04:28

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_aparienciaconfig_estilo_tarjeta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='color_desc_tarjeta',
            field=colorfield.fields.ColorField(default='#52525B', image_field=None, max_length=25, samples=None, verbose_name='Color Descripción (Tarjetas)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='color_titulo_tarjeta',
            field=colorfield.fields.ColorField(default='#18181B', image_field=None, max_length=25, samples=None, verbose_name='Color Título (Tarjetas)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='fuente_tarjetas',
            field=models.CharField(choices=[('"Poppins", sans-serif', 'Fuente Principal (Poppins)'), ('"Lora", serif', 'Fuente Elegante (Lora)'), ('"Segoe UI", sans-serif', 'Fuente Moderna (Segoe UI)')], default='"Poppins", sans-serif', max_length=50, verbose_name='Tipografía de Tarjetas'),
        ),
    ]
