# Generated by Django 5.2.7 on 2025-10-28 04:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_aparienciaconfig_color_desc_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='card_btn_principal_fondo',
            field=colorfield.fields.ColorField(default='#78857A', image_field=None, max_length=25, samples=None, verbose_name='[Tarjeta] Color Principal (Fondo)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='card_btn_principal_hover',
            field=colorfield.fields.ColorField(default='#647066', image_field=None, max_length=25, samples=None, verbose_name='[Tarjeta] Color Principal (Hover)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='card_btn_principal_texto',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='[Tarjeta] Color Principal (Texto)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='card_btn_secundario_borde',
            field=colorfield.fields.ColorField(default='#78857A', image_field=None, max_length=25, samples=None, verbose_name='[Tarjeta] Color Secundario (Borde)'),
        ),
    ]
