# Generated by Django 5.2.7 on 2025-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_aparienciaconfig_card_btn_principal_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparienciaconfig',
            name='estilo_tarjeta_producto',
            field=models.CharField(choices=[('simple', 'Estilo Simple (Actual)'), ('hot_sale', 'Estilo "Hot Sale" (Con insignia)'), ('harvest', 'Estilo "Harvest" (Vase)')], default='simple', help_text='Elige el diseño que se usará para mostrar los productos en el catálogo.', max_length=20, verbose_name='Estilo de Tarjetas de Producto'),
        ),
    ]
