# Generated by Django 5.2.7 on 2025-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0009_alter_aparienciaconfig_estilo_tarjeta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='logo_alt_text',
            field=models.CharField(default='Logo de NutriTienda', help_text='Texto descriptivo del logo para accesibilidad.', max_length=100, verbose_name='Texto Alternativo (ALT)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='logo_ancho',
            field=models.PositiveIntegerField(default=150, help_text='Define el ancho máximo del logo en el header.', verbose_name='Ancho del Logo (en píxeles)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='Sube el logo principal (ej. PNG, JPG).', null=True, upload_to='logos/', verbose_name='Logo Principal (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Opcional. Sube un logo SVG (se priorizará sobre el PNG/JPG si existe).', null=True, upload_to='logos/', verbose_name='Logo Vectorial (SVG)'),
        ),
    ]
