# Generated by Django 5.2.7 on 2025-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_aparienciaconfig_logo_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='logo_alt_text',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='logo_ancho',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='logo_principal',
        ),
        migrations.RemoveField(
            model_name='aparienciaconfig',
            name='logo_svg',
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='logo_sitio',
            field=models.ImageField(blank=True, help_text="Sube el logo que aparecerá en el menú. Si no subes ninguno, se mostrará el texto 'Mi Tienda'. Se ajustará a 50px de alto.", null=True, upload_to='logos/', verbose_name='Logo del Sitio (Navbar)'),
        ),
    ]
