# Generated by Django 5.2.7 on 2025-10-31 19:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_remove_aparienciaconfig_logo_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='color_carrito_activo',
            field=colorfield.fields.ColorField(default='#E74C3C', help_text='Color del círculo numérico del carrito cuando tiene productos.', image_field=None, max_length=25, samples=None, verbose_name='Color Contador Carrito (con items)'),
        ),
    ]
