# Generated by Django 5.2.7 on 2025-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_aparienciaconfig_color_carrito_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(help_text='Un párrafo corto explicando el servicio.', verbose_name='Descripción Corta')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (ej: 25000.00)')),
                ('tipo_servicio', models.CharField(choices=[('TURNO', 'Consulta (Enlaza al Calendario de Turnos)'), ('RECETARIO', 'Recetario (Genera un Pago Directo)')], default='TURNO', help_text="Esto define qué hace el botón 'Contratar': enlazar al calendario o generar un pago.", max_length=10, verbose_name='Tipo de Botón')),
                ('icono', models.CharField(blank=True, help_text="Opcional. Ej: 'fas fa-calendar-alt' o 'fas fa-book-open'", max_length=50, null=True, verbose_name='Icono (Clase de Font Awesome)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Define el orden de aparición (menor número primero).')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar este servicio en la página?')),
            ],
            options={
                'verbose_name': 'Servicio / Plan',
                'verbose_name_plural': 'Servicios / Planes',
                'ordering': ['orden'],
            },
        ),
    ]
