# Generated by Django 5.2.7 on 2025-11-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparienciaconfig',
            name='footer_col_contacto_texto',
            field=models.TextField(blank=True, default='¿Tienes una consulta? <br> ¡Escríbeme!', max_length=200, verbose_name='Texto Columna Contacto'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='footer_col_contacto_titulo',
            field=models.CharField(default='Contacto', max_length=50, verbose_name='Título Columna Contacto'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='footer_link_instagram',
            field=models.URLField(blank=True, help_text='URL completa (ej: https://instagram.com/...)', max_length=255, null=True, verbose_name='Enlace Instagram'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='footer_link_whatsapp',
            field=models.URLField(blank=True, help_text='URL completa (ej: https://wa.me/123456...)', max_length=255, null=True, verbose_name='Enlace WhatsApp'),
        ),
        migrations.AddField(
            model_name='aparienciaconfig',
            name='footer_texto_creditos',
            field=models.CharField(default='Luis Jiménez', max_length=100, verbose_name='Nombre Creador (Footer)'),
        ),
    ]
