# Generated by Django 5.2.7 on 2025-11-03 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_aparienciaconfig_footer_col_contacto_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparienciaconfig',
            name='logo_sitio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo_sitio'),
        ),
        migrations.AlterField(
            model_name='carruselimagen',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='carrusel_imagen'),
        ),
        migrations.AlterField(
            model_name='herosectionconfig',
            name='imagen_fondo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_imagen'),
        ),
    ]
