# Generated by Django 5.2.7 on 2025-11-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0015_alter_aparienciaconfig_logo_sitio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aparienciaconfig",
            name="logo_sitio",
        ),
        migrations.RemoveField(
            model_name="carruselimagen",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="herosectionconfig",
            name="imagen_fondo",
        ),
    ]
