# Generated by Django 5.2.7 on 2025-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0016_remove_aparienciaconfig_logo_sitio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aparienciaconfig",
            name="logo_sitio",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos/",
                verbose_name="Logo del Sitio (Navbar)",
            ),
        ),
        migrations.AddField(
            model_name="carruselimagen",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="carrusel/",
                verbose_name="Imagen del carrusel",
            ),
        ),
        migrations.AddField(
            model_name="herosectionconfig",
            name="imagen_fondo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hero_images/",
                verbose_name="Imagen de Fondo",
            ),
        ),
    ]
