# Generated by Django 5.2.7 on 2025-11-06 23:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_aparienciaconfig_logo_sitio_carruselimagen_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparienciaconfig',
            name='logo_sitio',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del Sitio (Navbar)'),
        ),
        migrations.AlterField(
            model_name='carruselimagen',
            name='imagen',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='carrusel/', verbose_name='Imagen del carrusel'),
        ),
        migrations.AlterField(
            model_name='herosectionconfig',
            name='imagen_fondo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Imagen de Fondo'),
        ),
    ]
