# Generated by Django 5.2.7 on 2025-12-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_alter_aparienciaconfig_logo_sitio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Instrucciones de Transferencia'), ('DESPACHADO', 'Pedido Despachado (Envío)'), ('PAGO_CONFIRMADO', 'Pago Confirmado (Recibo)')], max_length=50, unique=True, verbose_name='Tipo de Email')),
                ('asunto', models.CharField(help_text='Puedes usar variables como {{ pedido.id }}', max_length=200)),
                ('contenido', models.TextField(help_text='\n        Escribe aquí el contenido. Puedes usar HTML simple (<b>negrita</b>, <br> saltos).\n        <br><strong>Variables Disponibles:</strong>\n        <ul>\n            <li>{{ pedido.id }} - ID del pedido</li>\n            <li>{{ pedido.total }} - Total a pagar</li>\n            <li>{{ cliente.first_name }} - Nombre del cliente</li>\n            <li>{{ datos_pago.cbu_alias }} - Alias/CBU</li>\n            <li>{{ codigo_seguimiento }} - (Solo para envíos)</li>\n        </ul>\n        ', verbose_name='Cuerpo del Email (HTML)')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
