# Generated by Django 5.2.7 on 2025-12-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0019_emailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_consulta', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Precio de Consulta (Turno)')),
                ('precio_recetario_mensual', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='Precio Recetario (Mensual)')),
            ],
            options={
                'verbose_name': 'Configuración de Precios',
                'verbose_name_plural': 'Configuración de Precios',
            },
        ),
    ]
