# Generated by Django 5.2.7 on 2025-10-22 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0004_categoria_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, help_text='Código de seguimiento manual de Andreani/Correo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio_elegido',
            field=models.CharField(blank=True, help_text='Método de envío que seleccionó el cliente (ej: Andreani)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_postal_envio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('en_preparacion', 'En Preparación'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
