# Generated by Django 5.2.7 on 2025-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_pedido_options_pedido_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, help_text='Código de seguimiento manual', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_envio_elegido',
            field=models.CharField(blank=True, default='Retiro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total final (Subtotal + Envío)', max_digits=10),
        ),
    ]
