# Generated by Django 5.2.7 on 2025-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('ingredientes', models.TextField(help_text='Lista los ingredientes separados por comas.')),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
