# Generated by Django 5.2.7 on 2025-11-03 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20251009_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receta_imagen'),
        ),
    ]
