# Generated by Django 5.2.7 on 2025-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0003_alter_receta_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receta",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="recetas/"),
        ),
    ]
