# Generated by Django 5.2.7 on 2025-10-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Elige el día de la semana para esta regla.')),
                ('hora_inicio', models.TimeField(help_text='Formato: HH:MM')),
                ('hora_fin', models.TimeField(help_text='Formato: HH:MM')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Disponibilidad',
                'verbose_name_plural': 'Reglas de Disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='TurnoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno Reservado',
                'verbose_name_plural': 'Turnos Reservados',
            },
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
