# Generated by Django 5.2.7 on 2025-12-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_regladisponibilidad_turnoreservado_delete_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladisponibilidad',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Elige el día de la semana.'),
        ),
        migrations.AlterField(
            model_name='turnoreservado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('esperando_confirmacion', 'Esperando Confirmación del Paciente')], default='pendiente', max_length=30),
        ),
    ]
