# Generated by Django 5.2.7 on 2025-12-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_celiaco',
            field=models.BooleanField(default=False, verbose_name='Soy Celíaco (Sin TACC)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='es_vegano',
            field=models.BooleanField(default=False, verbose_name='Soy Vegano'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='es_vegetariano',
            field=models.BooleanField(default=False, verbose_name='Soy Vegetariano'),
        ),
    ]
