# Generated by Django 5.2.7 on 2025-12-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_es_celiaco_perfil_es_vegano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='es_cliente_activo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='suscripcion_activa_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Suscripción'),
        ),
    ]
