# Generated by Django 5.2.7 on 2025-10-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
    ]
