# Generated by Django 5.2.7 on 2025-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
