# Generated by Django 5.2.7 on 2025-11-06 23:53

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
