# Generated by Django 5.2.7 on 2025-12-04 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_sin_tacc',
            field=models.BooleanField(default=False, verbose_name='Apto Celíaco (Sin TACC)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegano',
            field=models.BooleanField(default=False, verbose_name='Apto Vegano'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegetariano',
            field=models.BooleanField(default=False, verbose_name='Apto Vegetariano'),
        ),
        migrations.AddField(
            model_name='producto',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
