# Generated by Django 5.2.7 on 2025-12-12 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('peso_actual', models.DecimalField(decimal_places=2, help_text='En Kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='En Metros (ej: 1.75)', max_digits=4)),
                ('realizo_antropometria', models.BooleanField(default=False, verbose_name='¿Se realizó Antropometría ISAK?')),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Grasa')),
                ('porcentaje_musculo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Músculo')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura (cm)')),
                ('cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cadera (cm)')),
                ('sumatoria_pliegues', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sumatoria 6 Pliegues (mm)')),
                ('notas_evolucion', models.TextField(blank=True, null=True, verbose_name='Notas de la Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='panel_gestor.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
